#!/usr/bin/env bash

set -e

# Set ZSH as default shell
sudo chsh -s /usr/bin/zsh

# Debian Buster has a old version of neovim so we need to install the AppImage
sudo apt-get install -y libfuse2

sudo apt install fuse -y
sudo groupadd fuse
user="$(whoami)"
sudo usermod -a -G fuse $user

wget https://github.com/neovim/neovim/releases/latest/download/nvim.appimage
chmod u+x nvim.appimage
sudo mv nvim.appimage /usr/local/bin/nvim

echo "Neovim installed"

# Use dotbot for the dotfiles
CONFIG="install.conf.json"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"

echo "dotbot ran"

# Update node to a decent version
curl -fsSL https://deb.nodesource.com/setup_16.x | bash -
sudo apt-get install -y nodejs

echo "Node installed"

# Update npm
npm install -g npm@latest

echo "NPM updated"

# Start using latest node version
n latest
echo "NPM using latest"

# Install neovim LSP packages
npm install -g \
  typescript-language-server \
  vscode-langservers-extracted

echo "Neovim LSP packages installed"

# Install vim plugins
/usr/local/bin/nvim +'PlugInstall --sync' +qa

# Update path after installing latest node
PATH="$PATH"
