export DEFAULT_USER="${USER:-$(id -un)}"
export DOTFILES_ROOT="${${(%):-%N}:A:h:h:h}"
export ZSH="$HOME/.oh-my-zsh"
export ZSH_CUSTOM="$DOTFILES_ROOT/home/zsh/oh-my-zsh"
export EDITOR="${EDITOR:-nvim}"

typeset -U path PATH
path=(
  "$HOME/.local/bin"
  "$HOME/bin"
  "$DOTFILES_ROOT/bin"
  $path
)

if [[ -x /opt/homebrew/bin/brew ]]; then
  eval "$(/opt/homebrew/bin/brew shellenv)"
elif [[ -x /home/linuxbrew/.linuxbrew/bin/brew ]]; then
  eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
elif (( $+commands[brew] )); then
  eval "$(brew shellenv)"
fi

ZSH_THEME="robbyrussell"
if [[ "${CODESPACES:-false}" == "true" ]]; then
  ZSH_THEME="cloud"
fi

COMPLETION_WAITING_DOTS="true"

plugins=(
  git
  bundler
  rake
  ruby
  encode64
  npm
  zsh-autosuggestions
  zsh-syntax-highlighting
)

[[ "$OSTYPE" == darwin* ]] && plugins+=(macos)
(( $+commands[brew] )) && plugins+=(brew)

source "$ZSH/oh-my-zsh.sh"

if (( $+commands[fd] )); then
  export FZF_DEFAULT_COMMAND='fd --type f'
elif (( $+commands[fdfind] )); then
  export FZF_DEFAULT_COMMAND='fdfind --type f'
fi

export FZF_DEFAULT_OPTS="--color fg:#ebdbb2,bg:#282828,hl:#fabd2f,fg+:#ebdbb2,bg+:#3c3836,hl+:#fabd2f --color info:#83a598,prompt:#bdae93,spinner:#fabd2f,pointer:#83a598,marker:#fe8019,header:#665c54 --layout=reverse --margin=2,5"

if (( $+commands[bat] )); then
  export FZF_CTRL_T_OPTS="--preview 'bat --color=always --line-range :500 -- {}'"
  alias preview="fzf --preview 'bat --color=always -- {}'"
elif (( $+commands[batcat] )); then
  export FZF_CTRL_T_OPTS="--preview 'batcat --color=always --line-range :500 -- {}'"
  alias preview="fzf --preview 'batcat --color=always -- {}'"
fi

fzf_git_log() {
  local selection hash

  selection=$(
    git log --color=always \
      --format='%H%x09%C(auto)%h%d %s %Cgreen(%cr) %Cblue<%an>' "$@" |
      fzf --ansi --no-sort --delimiter=$'\t' --with-nth=2.. \
        --preview 'git show --color=always {1} --'
  ) || return

  hash="${selection%%$'\t'*}"
  git show "$hash" --
}

rebaseorigin() {
  local branch
  branch=$(git symbolic-ref --quiet --short HEAD) || return
  git fetch origin && git rebase "origin/$branch"
}

alias gll='fzf_git_log'
alias rebasemain='git fetch origin && git rebase origin/main'
alias rebasemaster='git fetch origin && git rebase origin/master'
alias clr='clear'
alias cls='clear'
alias gitprune='git remote prune origin'
alias gst='git status'
alias gut='git'
alias work='cd ~/workspace'
alias opr='gh pr create --web'
alias orepo='gh repo view --web'
alias help='tldr'

if (( $+commands[eza] )); then
  alias ls='eza'
  alias ll='eza -lagh --git'
else
  alias ll='ls -lAFh'
fi

if [[ -n "${TTY:-}" ]]; then
  export GPG_TTY="$TTY"
fi

export GOPATH="${GOPATH:-$HOME/go}"
path+=("$GOPATH/bin")

[[ -r "$HOME/.fzf.zsh" ]] && source "$HOME/.fzf.zsh"

if (( $+commands[mise] )); then
  eval "$(mise activate zsh)"
fi

[[ -r "$HOME/.zshrc.local" ]] && source "$HOME/.zshrc.local"

export DISABLE_AUTO_TITLE=true
