[general]
live_config_reload = true

[window]
decorations = "none"

[bell]
duration = 0

[colors.bright]
black = "#969896"
blue = "#b4b7b4"
cyan = "#a3685a"
green = "#282a2e"
magenta = "#e0e0e0"
red = "#de935f"
white = "#ffffff"
yellow = "#373b41"

[colors.cursor]
cursor = "#c5c8c6"
text = "#1d1f21"

[colors.normal]
black = "#1d1f21"
blue = "#81a2be"
cyan = "#8abeb7"
green = "#b5bd68"
magenta = "#b294bb"
red = "#cc6666"
white = "#c5c8c6"
yellow = "#f0c674"

[colors.primary]
background = "#1d1f21"
foreground = "#c5c8c6"

[font]
size = 10.0

[font.bold]
family = "Hack Nerd Font Mono"
style = "Medium"

[font.italic]
family = "Hack Nerd Font Mono"

[font.normal]
family = "Hack Nerd Font Mono"

[window.padding]
x = 2
y = 2
